language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
  - adb push eventbus\build\outputs\apk\eventbus-debug-androidTest-unaligned.apk /data/local/tmp/com.pgssoft.gimbus.test
  - adb shell pm install -r "/data/local/tmp/com.pgssoft.gimbus.test"
  - adb shell am instrument -w -r   -e debug false com.pgssoft.gimbus.test/android.test.InstrumentationTestRunner